"use client";
import {useEffect,useRef,useState} from 'react';
import {Leaf,MapPin,Sun,Users,Settings,Maximize,Compass,ArrowUpRight,Map,Smartphone,HelpCircle,MessageCircle,Car,Camera,Radio,Volume2,X,Send,ChevronRight,Footprints} from 'lucide-react';
import {createWorld,type World} from './world';
import TouchControls from './touch-controls';
type Message={id:string;name:string;text:string};
const places=[{name:'Fort Kochi',x:0,z:0,desc:'Your coastal home'},{name:'Alappuzha',x:0,z:180,desc:'Backwaters & houseboats'},{name:'Munnar',x:200,z:-180,desc:'Into the green hills'},{name:'Varkala',x:0,z:350,desc:'The long way to the sea'}];
export default function Home(){
const mount=useRef<HTMLDivElement>(null),game=useRef<World|null>(null),id=useRef(''),sessionToken=useRef(''),audio=useRef<AudioContext|null>(null);
const [ready,setReady]=useState(false),[panel,setPanel]=useState(''),[app,setApp]=useState(''),[speed,setSpeed]=useState(0),[driving,setDriving]=useState(true),[time,setTime]=useState('14:30'),[pos,setPos]=useState({x:0,z:0}),[online,setOnline]=useState(0),[connected,setConnected]=useState(false),[messages,setMessages]=useState<Message[]>([]),[draft,setDraft]=useState(''),[name,setName]=useState('Traveler'),[night,setNight]=useState(false),[quality,setQuality]=useState('High'),[radio,setRadio]=useState(false),[toast,setToast]=useState(''),[place,setPlace]=useState('Fort Kochi'),[error,setError]=useState('');
const notify=(text:string)=>{setToast(text);setTimeout(()=>setToast(''),4000)};
useEffect(()=>{id.current=crypto.randomUUID();sessionToken.current=crypto.randomUUID();try{game.current=createWorld(mount.current!,s=>{setReady(true);setSpeed(s.speed);setDriving(s.driving);setTime(s.time);setPos({x:s.x,z:s.z})})}catch(e){queueMicrotask(()=>setError('3D graphics could not start. Enable browser hardware acceleration and reload.'));console.error(e)}return()=>game.current?.dispose()},[]);
useEffect(()=>{if(!ready)return;let stopped=false;let timer:ReturnType<typeof setTimeout>;async function sync(){try{const r=await fetch('/api/world',{method:'POST',headers:{'Content-Type':'application/json'},signal:AbortSignal.timeout(15000),body:JSON.stringify({id:id.current,token:sessionToken.current,name,...game.current?.position()})});if(r.status===401){id.current=crypto.randomUUID();sessionToken.current=crypto.randomUUID()}if(!r.ok)throw Error();const d=await r.json() as {players:{id:string;name:string;x:number;z:number;angle:number;driving:boolean}[];messages:Message[]};if(stopped)return;setConnected(true);setOnline(d.players.length);setMessages(d.messages);game.current?.peers(d.players.filter((p:{id:string})=>p.id!==id.current))}catch{if(!stopped){setConnected(false);setOnline(0)}}if(!stopped)timer=setTimeout(sync,500)}sync();return()=>{stopped=true;clearTimeout(timer)}},[ready,name]);
useEffect(()=>{if(game.current)game.current.paused=!!panel;const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement).tagName==='INPUT')return;const k=e.key.toLowerCase();if(k==='escape'){setPanel('');setApp('')}if(k==='p'){setPanel(p=>p==='phone'?'':'phone');setApp('')}if(k==='m')setPanel(p=>p==='map'?'':'map');if(k==='t'){e.preventDefault();setPanel('chat')}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[panel]);
useEffect(()=>()=>{audio.current?.close()},[]);
async function send(){if(!draft.trim())return;try{const r=await fetch('/api/world',{method:'POST',headers:{'Content-Type':'application/json'},signal:AbortSignal.timeout(15000),body:JSON.stringify({id:id.current,token:sessionToken.current,name,...game.current?.position(),message:draft})});if(!r.ok)throw Error();const d=await r.json() as {players:{id:string;name:string;x:number;z:number;angle:number;driving:boolean}[];messages:Message[]};setMessages(d.messages);setDraft('')}catch{notify('Could not send. Please try again.')}}
function toggleRadio(){if(radio){audio.current?.close();audio.current=null;setRadio(false);return}const ctx=new AudioContext();audio.current=ctx;[130.81,164.81,196,261.63].forEach((f,i)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=f;g.gain.value=.012;o.connect(g);g.connect(ctx.destination);o.start(ctx.currentTime+i*.2)});setRadio(true)}
function travel(p:typeof places[number]){game.current?.travel(p.x,p.z);setPlace(p.name);setPanel('');notify(`Arrived in ${p.name}`)}

return <main className="game-shell"><div ref={mount} className="world-canvas"/><div className="vignette"/>{!ready&&!error&&<div className="world-loading"><Leaf size={30}/><b>Your road is waiting.</b><span>Preparing the coast…</span></div>}
<header className="topbar"><div className="brand"><span className="brand-mark"><Leaf size={26}/></span><span>KERALA<span className="brand-world">WORLD</span></span><span className="alpha">EARLY ACCESS</span></div><div className="top-center"><i className="live-dot"/>{connected?'LIVE WORLD':'CONNECTING…'}<span className="divider"/><Users size={14}/><b>{String(online).padStart(2,'0')}</b><span className="muted">online</span></div><div className="top-actions"><button aria-label="Controls" onClick={()=>setPanel('guide')}><HelpCircle size={18}/></button><button aria-label="Settings" onClick={()=>setPanel('settings')}><Settings size={18}/></button><button aria-label="Fullscreen" onClick={()=>{if(!document.fullscreenElement)document.documentElement.requestFullscreen().catch(()=>notify('Fullscreen unavailable'));else document.exitFullscreen()}}><Maximize size={18}/></button><span className="avatar">{name.slice(0,2).toUpperCase()}</span></div></header>
<section className="location"><div className="eyebrow"><i/> GOD’S OWN COUNTRY</div><h1>{place}<span>, Kerala</span></h1><p><MapPin size={13}/> {pos.z>120?'Backwater Road':'Beach Road'}<span>•</span>Free roam</p></section>
<div className="weather glass"><Sun size={23}/><div><b>{time}</b><span>{Number(time.split(':')[0])>=18||Number(time.split(':')[0])<6?'Moonlit skies':'Mostly sunny'} · 28°C</span></div><i/><span className="day-label">DAY 01</span></div>
<section className="adventure glass"><span className="adventure-icon"><Compass size={23}/></span><div><span className="eyebrow">THE WORLD IS YOURS</span><h3>Take the scenic route.</h3><p>No rush. Just you and the open road.</p><button onClick={()=>setPanel('map')}>Explore Kerala <ArrowUpRight size={15}/></button></div><button className="small-close" aria-label="Dismiss tip" onClick={e=>e.currentTarget.parentElement?.classList.add('hidden')}>×</button></section>
<div className="scene-label"><span className="pin-ring"><MapPin size={19}/></span><b>Fort Kochi Beach</b><small>COASTAL DISTRICT</small></div><div className="mode-pill"><i className="live-dot"/>{driving?'FREE ROAM · DRIVING':'FREE ROAM · ON FOOT'}</div>
<section className="bottom-left"><button className="minimap glass" aria-label="Open Kerala map" onClick={()=>setPanel('map')}><MapArt/><span className="north">N</span><span className="map-dot" style={{transform:`translate(${pos.x/15}px,${pos.z/15}px)`}}>▲</span><span className="map-expand"><Maximize size={13}/></span><span className="map-caption">FORT KOCHI <ChevronRight size={12}/></span></button><div className="vitals"><span><i className="health"/>100</span><span><i className="stamina"/>100</span><span className="coordinates">{Math.round(pos.x)}, {Math.round(pos.z)}</span></div></section>
<section className="chat-preview"><div className="chat-heading"><MessageCircle size={14}/><b>World chat</b><span>{online} online</span></div><div className="preview-lines">{messages.length?messages.slice(-3).map(m=><p key={m.id}><b>{m.name}</b><span>{m.text}</span></p>):<p><b>Welcome</b><span>The coast is yours. Say hello!</span></p>}</div><button onClick={()=>setPanel('chat')}>Press <kbd>T</kbd> to chat <MessageCircle size={13}/></button></section>
<section className="vehicle-hud"><div className="vehicle-name">{driving?<Car size={15}/>:<Footprints size={15}/>}<span>{driving?'COASTLINE CLASSIC':'ON FOOT'}</span><i/></div><div className="speed"><b>{String(speed).padStart(3,'0')}</b><span>KM/H<small>{driving?'D  /  AUTO':'WALKING'}</small></span></div><div className="speed-track"><i style={{width:`${Math.min(speed,100)}%`}}/></div><div className="vehicle-footer"><span>▰ <b>86</b><small> %</small></span><button onClick={()=>game.current?.toggleCar()}><kbd>E</kbd> {driving?'Exit vehicle':'Enter vehicle'}</button></div></section>
<TouchControls world={game} driving={driving} hidden={!!panel||!ready} open={p=>{setApp('');setPanel(p)}}/><footer className="bottom-bar"><div className="control-hints"><span><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> Move</span><span><kbd>SPACE</kbd> Brake / jump</span><span><kbd>↔</kbd> Drag to look</span></div><nav><button onClick={()=>setPanel('map')}><Map size={17}/>Map<kbd>M</kbd></button><button onClick={()=>{setPanel('phone');setApp('')}}><Smartphone size={17}/>Phone<kbd>P</kbd></button><button onClick={()=>setPanel('guide')}><HelpCircle size={17}/>Controls</button></nav></footer>
{toast&&<div className="toast">{toast}</div>}{error&&<div className="modal-backdrop"><div className="modal"><h2>Graphics unavailable</h2><p>{error}</p></div></div>}
{panel&&<div className={`modal-backdrop ${panel==='phone'?'phone-backdrop':''}`} onClick={()=>setPanel('')}><section className={panel==='phone'?'phone':'modal'} onClick={e=>e.stopPropagation()}><header className="modal-header"><div><span className="eyebrow">KERALA WORLD</span><h2>{panel==='phone'?(app||'Your phone'):panel==='map'?'Find your next adventure':panel==='chat'?'World chat':panel==='settings'?'Make yourself at home':'The road is yours'}</h2></div><button aria-label="Close" onClick={()=>setPanel('')}><X size={20}/></button></header>
{(panel==='map'||(panel==='phone'&&app==='Map'))&&<WorldMap pos={pos} onTravel={travel}/>}
{panel==='guide'&&<div className="guide-grid">{[['W A S D','Drive or walk'],['Drag mouse','Look around'],['E','Enter / exit nearby car'],['Space','Brake / jump'],['Shift','Sprint on foot'],['P','Open phone'],['M','Open map'],['T','World chat'],['Escape','Close menu']].map(([k,v])=><div key={k}><kbd>{k}</kbd><span>{v}</span></div>)}<p>Explore the coast or head inland. Players on the same server can see each other and chat.</p></div>}
{(panel==='chat'||(panel==='phone'&&app==='Messages'))&&<><div className="message-list">{!messages.length&&<p className="empty-state">A good journey starts with hello.<br/>Send the first message to the world.</p>}{messages.map(m=><div key={m.id}><b>{m.name}</b><p>{m.text}</p></div>)}</div><form className="chat-form" onSubmit={e=>{e.preventDefault();send()}}><input autoFocus maxLength={240} value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Say something to the world…"/><button aria-label="Send message"><Send size={18}/></button></form></>}
{(panel==='settings'||(panel==='phone'&&app==='Settings'))&&<div className="settings-list"><label>Your traveler name<input value={name} maxLength={20} onChange={e=>setName(e.target.value)}/></label><label>Graphics<select value={quality} onChange={e=>{setQuality(e.target.value);game.current?.quality(e.target.value)}}><option>High</option><option>Balanced</option><option>Low</option></select></label><button onClick={()=>{setNight(!night);game.current?.setNight(!night)}}><Sun size={20}/>{night?'Switch to daylight':'Switch to night'}<ChevronRight size={17}/></button><button onClick={toggleRadio}><Volume2 size={20}/>{radio?'Turn radio off':'Turn radio on'}<ChevronRight size={17}/></button><p className="fine-print">Time advances automatically. World sessions and chat reset when the server restarts.</p></div>}
{panel==='phone'&&!app&&<><div className="phone-clock">{time}<span>Friday, September 11</span><small><Sun size={14}/> Kochi · 28°</small></div><div className="phone-apps">{[{n:'Map',I:Map,c:'#8aa886'},{n:'Messages',I:MessageCircle,c:'#72ae87'},{n:'Garage',I:Car,c:'#ca9c69'},{n:'Camera',I:Camera,c:'#9ca5b0'},{n:'Radio',I:Radio,c:'#b98a91'},{n:'Settings',I:Settings,c:'#8299ab'}].map(a=><button key={a.n} onClick={()=>{if(a.n==='Camera'){game.current?.photo();notify('Photo saved to downloads')}else setApp(a.n)}}><span style={{background:a.c}}><a.I size={25}/></span>{a.n}</button>)}</div><div className="phone-note"><Leaf size={18}/>Less scrolling. More exploring.</div></>}
{panel==='phone'&&app==='Garage'&&<div className="garage"><Car size={80}/><h3>Coastline Classic</h3><p>A little vintage. A lot of freedom.</p><div className="paint-colors">{['#ebdfc7','#c96948','#3d7177','#414343'].map(c=><button key={c} aria-label={`Paint ${c}`} style={{background:c}} onClick={()=>{game.current?.paint(c);notify('New paint, same open road.')}}/>)}</div><button className="primary" onClick={()=>{game.current?.summon();setPanel('');notify('Your car is ready')}}>Bring my car here<Car size={17}/></button></div>}
{panel==='phone'&&app==='Radio'&&<div className="garage"><Radio size={70}/><h3>Backwater FM</h3><p>Soft ambient tones for slow days.</p><button className="primary" onClick={toggleRadio}>{radio?'Pause radio':'Play radio'}<Volume2 size={17}/></button></div>}
{panel==='phone'&&!!app&&<button className="phone-home" onClick={()=>setApp('')}>Back to home</button>}</section></div>}</main>
}
function MapArt(){return <svg className="map-art" viewBox="0 0 300 230" preserveAspectRatio="xMidYMid slice"><rect width="300" height="230" fill="#789c9c"/><path d="M112 -10L145 30 122 63 143 110 127 150 167 201 164 240H310V-10" fill="#b3b99e"/><path d="M195 -10L173 30 189 57 178 83 207 120 184 161 226 202 215 240" fill="none" stroke="#87a4a1" strokeWidth="15"/><g stroke="#dbd6bc" strokeWidth="5" fill="none"><path d="M145 -10L155 42 147 73 165 121 150 151 186 205 189 240"/><path d="M126 67L300 35M139 112L300 95M144 153L300 145M169 199L300 206M246 0L236 64 259 125 247 230"/></g><g fill="#97a188">{[0,1,2,3,4,5].map(i=><g key={i}><rect x={209+i%2*55} y={i*37} width="18" height="23" rx="2"/><rect x={158+i%2*36} y={i*39+8} width="10" height="14" rx="1"/></g>)}</g><path d="M150 76L164 119 152 150" stroke="#f8e7a2" strokeWidth="4" fill="none"/></svg>}




function WorldMap({pos,onTravel}:{pos:{x:number;z:number};onTravel:(p:typeof places[number])=>void}){return <><div className="large-map"><MapArt/><span className="sea-label">ARABIAN SEA</span><span className="land-label">KERALA</span><span className="map-dot large" style={{left:`${48+pos.x/10}%`,top:`${35+pos.z/10}%`}}>▲</span></div><div className="destinations">{places.map(p=><button key={p.name} onClick={()=>onTravel(p)}><MapPin size={17}/><span><b>{p.name}</b><small>{p.desc}</small></span><ArrowUpRight size={17}/></button>)}</div><p className="fine-print">A compact Kerala-inspired map. Select a place to fast travel.</p></>}

