import * as T from 'three';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
type Snapshot={speed:number;time:string;x:number;z:number;driving:boolean};
type Peer={id:string;x:number;z:number;angle:number;driving:boolean;name:string};
export type World={paused:boolean;input:(key:string,pressed:boolean)=>void;position:()=>{x:number;z:number;angle:number;driving:boolean};peers:(p:Peer[])=>void;toggleCar:()=>void;travel:(x:number,z:number)=>void;paint:(c:string)=>void;summon:()=>void;photo:()=>void;quality:(q:string)=>void;setNight:(n:boolean)=>void;dispose:()=>void};
export function createWorld(root:HTMLElement,update:(s:Snapshot)=>void):World{
const scene=new T.Scene();scene.background=new T.Color('#b4d8d6');scene.fog=new T.FogExp2('#b4d8d6',.0024);
const renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(matchMedia('(pointer: coarse)').matches?1:Math.min(devicePixelRatio,1.7));renderer.setSize(root.clientWidth,root.clientHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;root.appendChild(renderer.domElement);
const camera=new T.PerspectiveCamera(55,root.clientWidth/root.clientHeight,.2,1700);camera.position.set(15,9,22);
const hemi=new T.HemisphereLight('#d8f1ff','#71805a',2.2);scene.add(hemi);const sun=new T.DirectionalLight('#ffe1a5',3.4);sun.position.set(-95,160,70);sun.castShadow=true;sun.shadow.mapSize.set(matchMedia('(pointer: coarse)').matches?1024:2048,matchMedia('(pointer: coarse)').matches?1024:2048);Object.assign(sun.shadow.camera,{left:-150,right:150,top:150,bottom:-150,far:500});sun.shadow.bias=-.0005;scene.add(sun);scene.add(sun.target);
let seed=731;const rand=()=>{seed=(seed*16807)%2147483647;return(seed-1)/2147483646};
const mats=new Map<string,T.MeshStandardMaterial>();function mat(c:string){if(!mats.has(c))mats.set(c,new T.MeshStandardMaterial({color:c,roughness:.8}));return mats.get(c)!}
function box(w:number,h:number,d:number,c:string,x:number,y:number,z:number,parent:T.Object3D=scene){const m=new T.Mesh(new T.BoxGeometry(w,h,d),mat(c));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
function rod(a:T.Vector3,b:T.Vector3,r:number,c:string,parent:T.Object3D=scene){const dir=b.clone().sub(a);const m=new T.Mesh(new T.CylinderGeometry(r*.7,r,dir.length(),7),mat(c));m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),dir.normalize());m.castShadow=true;parent.add(m);return m}
box(1500,2,1600,'#527e60',300,-1.5,0);box(1000,1,1700,'#78afb0',-585,-1.4,0);box(60,.4,1400,'#dbd1ab',-58,-.2,0);box(17,.3,1300,'#727773',0,.02,0);box(2,.35,1300,'#c3bda6',10,.06,0);box(2,.35,1300,'#c3bda6',-10,.06,0);
for(let z=-640;z<640;z+=15){box(.22,.03,6,'#e6e0c0',0,.2,z);box(.18,.03,11,'#d6d1b6',7.5,.2,z);box(.18,.03,11,'#d6d1b6',-7.5,.2,z)}
for(let z=-240;z<500;z+=180){box(300,.32,12,'#7c8075',155,.05,z);for(let x=15;x<280;x+=15)box(6,.03,.2,'#dbd5b5',x,.24,z)}
// Fine wave ribbons across the Arabian Sea.
const waterLines=new T.Group();scene.add(waterLines);for(let i=0;i<140;i++){const line=box(5+rand()*65,.016,.14,'#a7c9c0',-95-rand()*370,-.78,rand()*1300-650,waterLines);line.material=new T.MeshStandardMaterial({color:'#c8dfce',transparent:true,opacity:.12+rand()*.15})}
const colliders:{x:number;z:number;w:number;d:number}[]=[];
function palm(x:number,z:number,h=14){const g=new T.Group();g.position.set(x,0,z);scene.add(g);rod(new T.Vector3(0,0,0),new T.Vector3(1.5,h,0),.29,'#8a8260',g);for(let i=0;i<7;i++){const a=i*Math.PI*2/7+rand()*.4;const vertices=[];for(let j=0;j<6;j++){const t=j/5;const r=t*8;const y=h+Math.sin(t*Math.PI)*2.2-t*3;const width=Math.sin(t*Math.PI)*1.1;vertices.push(1.5+Math.cos(a)*r+Math.sin(a)*width,y,Math.sin(a)*r-Math.cos(a)*width,1.5+Math.cos(a)*r-Math.sin(a)*width,y,Math.sin(a)*r+Math.cos(a)*width)}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(vertices,3));const indices=[];for(let j=0;j<5;j++){const k=j*2;indices.push(k,k+1,k+2,k+1,k+3,k+2)}geo.setIndex(indices);geo.computeVertexNormals();const m=new T.Mesh(geo,new T.MeshStandardMaterial({color:i%2?'#3d714b':'#5a8952',side:T.DoubleSide,roughness:.85}));m.castShadow=true;g.add(m)}}
for(let z=-580;z<590;z+=25){palm(-19-rand()*17,z,12+rand()*6);if(Math.abs(z%180)>18)palm(17+rand()*10,z+8,13+rand()*6)}
for(let i=0;i<100;i++){const x=50+rand()*290,z=rand()*1100-550;if(Math.abs(z%180)>25)palm(x,z,10+rand()*9)}
function house(x:number,z:number,w:number,h:number,d:number,c:string){box(w,h,d,c,x,h/2,z);colliders.push({x,z,w:w/2+1.5,d:d/2+1.5});const roof=new T.Mesh(new T.ConeGeometry(1,1,4),mat('#a9684d'));roof.rotation.y=Math.PI/4;roof.scale.set(w*.83,h*.46,d*.83);roof.position.set(x,h+h*.16,z);roof.castShadow=true;scene.add(roof);for(let dx=-w/2+2;dx<w/2;dx+=4){box(1.7,2.1,.13,'#446966',x+dx,h*.55,z+d/2+.07);box(1.9,.12,.26,'#e7d8b6',x+dx,h*.55-1.1,z+d/2+.13)}box(.15,h*.8,2,'#e7d8b6',x-w/2-.05,h*.45,z);box(w+2,.22,2.5,'#dfcda5',x,.3,z+d/2+1)}
for(let i=0;i<27;i++){const z=-520+i*39;if(Math.abs(z%180)<22)continue;house(40+rand()*7,z,17+rand()*10,6+rand()*6,17,['#e5d8ae','#e3b988','#c4cbb5','#e8dfc8'][i%4]);if(i%2===0)house(95,z+12,22,9,21,'#c4c3a0')}
// Inland lake and houseboats.
box(65,.1,650,'#71a49a',140,-.1,120);for(let i=0;i<4;i++){const z=90+i*75;box(8,1.6,23,'#755c3e',140,1,z);box(7,3.3,15,'#c7a977',140,3,z);box(8,.5,17,'#745c3c',140,5,z);for(let j=-1;j<=1;j++)box(.1,1.3,2.5,'#425c55',135.95,3,z+j*4)}
// Layered Western Ghats on the horizon.
for(let i=0;i<32;i++){const h=60+rand()*110;const m=new T.Mesh(new T.ConeGeometry(80+rand()*80,h,7),mat(i%2?'#6c9784':'#7ca28f'));m.position.set(360+rand()*310,h/2-8,-600+i*40);scene.add(m)}
// Chinese fishing nets along the waterfront.
for(let i=0;i<5;i++){const z=-85-i*48;box(14,.7,5,'#95886c',-68,1,z);const origin=new T.Vector3(-66,2,z);const top=new T.Vector3(-69,17,z);rod(origin,top,.23,'#685e48');rod(new T.Vector3(-81,4,z-10),top,.12,'#75694d');rod(new T.Vector3(-81,4,z+10),top,.12,'#75694d');rod(new T.Vector3(-59,4,z),top,.12,'#75694d');for(let n=0;n<=10;n++){const t=n/10;const pts=[new T.Vector3(-81,4,z-10+20*t),new T.Vector3(-88,2,z-10+20*t)];const geo=new T.BufferGeometry().setFromPoints(pts);scene.add(new T.Line(geo,new T.LineBasicMaterial({color:'#727b64',transparent:true,opacity:.5})))}}
// Roadside street lamps.
const lamps:T.Mesh[]=[];for(let z=-550;z<560;z+=55){rod(new T.Vector3(11,0,z),new T.Vector3(11,10,z),.13,'#5d6a61');rod(new T.Vector3(11,10,z),new T.Vector3(8,10,z),.1,'#5d6a61');lamps.push(box(1,.17,.65,'#fff0b3',8,9.9,z))}
// Merge stationary geometry by surface color to keep draw calls low.
scene.updateMatrixWorld(true);
const batches=new Map<string,{material:T.Material;geometries:T.BufferGeometry[];objects:T.Mesh[]}>();
scene.traverse(object=>{if(!(object instanceof T.Mesh)||object.parent===waterLines)return;const material=object.material as T.MeshStandardMaterial;const key=material.color.getHexString()+':'+material.side;let batch=batches.get(key);if(!batch){batch={material,geometries:[],objects:[]};batches.set(key,batch)}const geometry=object.geometry.clone().applyMatrix4(object.matrixWorld).toNonIndexed();geometry.deleteAttribute('uv');batch.geometries.push(geometry);batch.objects.push(object)});
for(const batch of batches.values()){const geometry=mergeGeometries(batch.geometries);if(!geometry)continue;const mesh=new T.Mesh(geometry,batch.material);mesh.castShadow=true;mesh.receiveShadow=true;scene.add(mesh);for(const object of batch.objects){object.removeFromParent();object.geometry.dispose();if(object.material!==batch.material&&!Array.isArray(object.material))object.material.dispose()}for(const item of batch.geometries)item.dispose()}
function makeCar(color:string){const g=new T.Group();box(2.65,.75,5.5,color,0,.94,0,g);box(2.5,.5,4.9,color,0,1.45,0,g);box(2.2,.95,2.65,'#456268',0,2.05,.1,g);box(2.25,.16,2.8,color,0,2.59,.1,g);for(const x of [-1.1,1.1])for(const z of [-1.12,1.28])box(.13,1.04,.15,color,x,2.06,z,g);box(2.3,.22,.17,'#b1b7ad',0,.68,2.79,g);box(2.3,.22,.17,'#b1b7ad',0,.68,-2.79,g);for(const x of [-.92,.92]){box(.55,.29,.08,'#f7e9b2',x,1.2,-2.78,g);box(.55,.26,.08,'#b65d47',x,1.17,2.78,g)}for(const x of [-1.32,1.32])for(const z of [-1.73,1.73]){const wheel=new T.Mesh(new T.CylinderGeometry(.59,.59,.31,16),mat('#303a36'));wheel.rotation.z=Math.PI/2;wheel.position.set(x,.64,z);wheel.castShadow=true;g.add(wheel);const hub=new T.Mesh(new T.CylinderGeometry(.3,.3,.33,12),mat('#b5b9ae'));hub.rotation.z=Math.PI/2;hub.position.copy(wheel.position);g.add(hub)}return g}
const car=makeCar('#ebdfc7');car.position.set(-3.8,.2,8);scene.add(car);const person=new T.Group();box(.7,.9,.38,'#cc8b59',0,1.35,0,person);box(.45,.45,.45,'#b88b68',0,2.02,0,person);box(.25,.8,.3,'#3c514c',-.2,.5,0,person);box(.25,.8,.3,'#3c514c',.2,.5,0,person);person.visible=false;scene.add(person);
let x=-3.8,z=8,angle=0,velocity=0,driving=true,orbit=.42,pitch=.14,drag=false,lookPointer:number|null=null,lastX=0,lastY=0,jump=0,jumpV=0,elapsed=0,last=performance.now(),frame=0,lastUI=0,nightOverride:boolean|null=null;const keys=new Set<string>();const remote=new Map<string,T.Group>();
function blocked(nx:number,nz:number){return nx< -49||nx>315||nz< -600||nz>600||(nx>107&&nx<174&&Math.abs(nz%180)>8)||colliders.some(c=>Math.abs(nx-c.x)<c.w&&Math.abs(nz-c.z)<c.d)}
const api:World={paused:false,input(key,pressed){if(!pressed){keys.delete(key);return}if(api.paused)return;keys.add(key);if(key===' '&&!driving&&jump===0)jumpV=6},position:()=>({x,z,angle,driving}),toggleCar(){if(driving){driving=false;x=car.position.x+3.5;z=car.position.z;velocity=0;person.visible=true}else if(Math.hypot(x-car.position.x,z-car.position.z)<9){driving=true;x=car.position.x;z=car.position.z;angle=car.rotation.y;person.visible=false}},travel(nx,nz){x=nx;z=nz;velocity=0;if(driving)car.position.set(x,.2,z);else person.position.set(x,0,z)},summon(){driving=true;person.visible=false;car.position.set(x,.2,z);velocity=0},paint(c){car.traverse(o=>{if(o instanceof T.Mesh&&o.material===mat('#ebdfc7'))o.material=new T.MeshStandardMaterial({color:c,roughness:.5})});const body=[car.children[0],car.children[1],car.children[3]];body.forEach(o=>(o as T.Mesh).material=new T.MeshStandardMaterial({color:c,roughness:.5}))},photo(){renderer.render(scene,camera);const a=document.createElement('a');a.download='kerala-world.png';a.href=renderer.domElement.toDataURL('image/png');a.click()},quality(q){renderer.setPixelRatio(q==='High'?Math.min(devicePixelRatio,1.7):q==='Balanced'?1:.7);renderer.shadowMap.enabled=q!=='Low'},setNight(n){nightOverride=n},peers(list){const ids=new Set(list.map(p=>p.id));for(const[id,g]of remote)if(!ids.has(id)){scene.remove(g);remote.delete(id)}for(const p of list){let g=remote.get(p.id);if(!g){g=new T.Group();const remoteCar=makeCar('#bd765c');const avatar=person.clone();avatar.visible=true;g.add(remoteCar,avatar);scene.add(g);remote.set(p.id,g)}g.position.set(p.x,.2,p.z);g.rotation.y=p.angle;g.children[0].visible=p.driving;g.children[1].visible=!p.driving}},dispose(){cancelAnimationFrame(frame);window.removeEventListener('resize',resize);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);renderer.domElement.removeEventListener('pointerdown',pointerDown);window.removeEventListener('pointerup',pointerUp);window.removeEventListener('pointercancel',pointerUp);window.removeEventListener('pointermove',pointerMove);scene.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();const materials=Array.isArray(o.material)?o.material:[o.material];materials.forEach(m=>m.dispose())}});renderer.dispose();root.replaceChildren()}};
const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement).matches('input,select,textarea')||api.paused)return;const k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();keys.add(k);if(k==='e'&&!e.repeat)api.toggleCar();if(k===' '&&!driving&&jump===0)jumpV=6};const up=(e:KeyboardEvent)=>keys.delete(e.key.toLowerCase());const blur=()=>keys.clear();const pointerDown=(e:PointerEvent)=>{if(lookPointer!==null||api.paused)return;lookPointer=e.pointerId;renderer.domElement.setPointerCapture(e.pointerId);drag=true;lastX=e.clientX;lastY=e.clientY};const pointerUp=(e:PointerEvent)=>{if(e.pointerId===lookPointer){drag=false;lookPointer=null}};const pointerMove=(e:PointerEvent)=>{if(drag&&e.pointerId===lookPointer&&!api.paused){orbit-=(e.clientX-lastX)*.006;pitch=T.MathUtils.clamp(pitch+(e.clientY-lastY)*.003,.02,.85);lastX=e.clientX;lastY=e.clientY}};function resize(){camera.aspect=root.clientWidth/root.clientHeight;camera.updateProjectionMatrix();renderer.setSize(root.clientWidth,root.clientHeight)}window.addEventListener('resize',resize);window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);renderer.domElement.addEventListener('pointerdown',pointerDown);window.addEventListener('pointerup',pointerUp);window.addEventListener('pointercancel',pointerUp);window.addEventListener('pointermove',pointerMove);
function animate(now:number){frame=requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.05);last=now;elapsed+=dt;if(!api.paused){const forward=(keys.has('w')||keys.has('arrowup')?1:0)-(keys.has('s')||keys.has('arrowdown')?1:0);const steer=(keys.has('a')||keys.has('arrowleft')?1:0)-(keys.has('d')||keys.has('arrowright')?1:0);if(driving){velocity+=forward*15*dt;velocity*=Math.exp(-(forward?.3:1.1)*dt);if(keys.has(' '))velocity*=Math.exp(-7*dt);velocity=T.MathUtils.clamp(velocity,-12,39);angle+=steer*dt*1.2*Math.min(Math.abs(velocity)/8,1)*Math.sign(velocity||1)}else{velocity=forward*(keys.has('shift')?11:5);angle+=steer*dt*2.2}const nx=x-Math.sin(angle)*velocity*dt,nz=z-Math.cos(angle)*velocity*dt;if(!blocked(nx,nz)){x=nx;z=nz}else velocity=0;jumpV-=15*dt;jump=Math.max(0,jump+jumpV*dt);if(jump===0)jumpV=0;if(driving){car.position.set(x,.2,z);car.rotation.y=angle}else{person.position.set(x,jump,z);person.rotation.y=angle}}else keys.clear();const dist=driving?15:9;const desired=new T.Vector3(x+Math.sin(angle+orbit)*dist,2.5+Math.sin(pitch)*dist,z+Math.cos(angle+orbit)*dist);camera.position.lerp(desired,1-Math.exp(-4*dt));camera.lookAt(x,driving?1.6:1.5,z-2);const hours=nightOverride===null?(14.5+elapsed/600)%24:nightOverride?22:14;const daylight=nightOverride===null?Math.max(.07,Math.sin((hours-6)/12*Math.PI)):nightOverride?.07:.9;hemi.intensity=.25+daylight*1.9;sun.intensity=daylight*3.6;const sky=new T.Color('#142e40').lerp(new T.Color('#bbdcd8'),daylight);scene.background=sky;(scene.fog as T.FogExp2).color.copy(sky);waterLines.position.z=Math.sin(elapsed*.25)*2;sun.position.set(x-95,160,z+70);sun.target.position.set(x,0,z);if(now-lastUI>150){update({speed:Math.round(Math.abs(velocity)*3.6),time:`${String(Math.floor(hours)).padStart(2,'0')}:${String(Math.floor(hours%1*60)).padStart(2,'0')}`,x,z,driving});lastUI=now}renderer.render(scene,camera)}frame=requestAnimationFrame(animate);return api;
}





